### ISSUE TITLE
Don't include manager.dat in download

### ISSUE THREAD

**Issue by fiwswe** [tscherter/number#1]
Currently the download link of the plugin contains an archive that includes the file manager.dat. This file should not be included as it contains information managed locally by DokuWiki.

It probably should not be included in the repository at all.

**Comment by tscherter** [comment]
Thx, Fixed

**Comment by fiwswe** [comment]
Nope, not fixed, sorry.

**Comment by tscherter** [comment]
sorry, did not sync after commiting the change.
